import { Notary } from "@/types";

export const NOTARIES: Notary[] = [
  {
    id: "not-001",
    name: "Sherzod Islomov",
    regionId: "tashkent-city",
    rating: 4.5,
    reviewCount: 608,
    specialties: ["Yer uchastkasi", "Ko'chmas mulk"],
    nextAvailable: "Bugun, 12:30",
    avatarSeed: "sherzod1",
  },
  {
    id: "not-002",
    name: "Sardor Xasanov",
    regionId: "tashkent",
    rating: 4.5,
    reviewCount: 488,
    specialties: ["Ariza-dalolatnomalar", "Ko'chmas mulk"],
    nextAvailable: "Bugun, 12:30",
    avatarSeed: "sardor2",
  },
  {
    id: "not-003",
    name: "Alisher G'aniyov",
    regionId: "andijan",
    rating: 4.6,
    reviewCount: 288,
    specialties: ["Ko'chmas mulk", "Notarial tarjima"],
    nextAvailable: "Indinga, 10:00",
    avatarSeed: "alisher3",
  },
  {
    id: "not-004",
    name: "Gulchehra Mahmudova",
    regionId: "fergana",
    rating: 5.0,
    reviewCount: 107,
    specialties: ["Biznes shartnomalari", "Ko'chmas mulk"],
    nextAvailable: "Ertaga, 17:30",
    avatarSeed: "gulchehra4",
  },
  {
    id: "not-005",
    name: "Kamola G'aniyova",
    regionId: "namangan",
    rating: 4.6,
    reviewCount: 375,
    specialties: ["Kredit hujjatlari", "Sud hujjatlari"],
    nextAvailable: "Ertaga, 17:30",
    avatarSeed: "kamola5",
  },
  {
    id: "not-006",
    name: "Zarina Ergashova",
    regionId: "sirdaryo",
    rating: 4.8,
    reviewCount: 441,
    specialties: ["Notarial tarjima", "Tashkiliy hujjatlar"],
    nextAvailable: "Bugun, 12:30",
    avatarSeed: "zarina6",
  },
  {
    id: "not-007",
    name: "Malika Qodirova",
    regionId: "jizzakh",
    rating: 4.7,
    reviewCount: 604,
    specialties: ["Notarial tarjima", "Ariza-dalolatnomalar"],
    nextAvailable: "Ertaga, 11:30",
    avatarSeed: "malika7",
  },
  {
    id: "not-008",
    name: "Muxlisa Sodiqova",
    regionId: "samarkand",
    rating: 4.6,
    reviewCount: 244,
    specialties: ["Meros ishlari", "Vasiyatnoma"],
    nextAvailable: "Bugun, 16:45",
    avatarSeed: "muxlisa8",
  },
  {
    id: "not-009",
    name: "Ulug'bek Nuriddinov",
    regionId: "bukhara",
    rating: 4.6,
    reviewCount: 134,
    specialties: ["Meros ishlari", "Nikoh shartnomasi"],
    nextAvailable: "Bugun, 12:30",
    avatarSeed: "ulugbek9",
  },
  {
    id: "not-010",
    name: "Zarina Abdullayeva",
    regionId: "navoiy",
    rating: 5.0,
    reviewCount: 491,
    specialties: ["Meros ishlari", "Kredit hujjatlari"],
    nextAvailable: "Bugun, 10:00",
    avatarSeed: "zarina10",
  },
  {
    id: "not-011",
    name: "Malika Yuldashova",
    regionId: "kashkadarya",
    rating: 4.7,
    reviewCount: 418,
    specialties: ["Notarial tarjima", "Meros ishlari"],
    nextAvailable: "Indinga, 10:00",
    avatarSeed: "malika11",
  },
  {
    id: "not-012",
    name: "Sanjar Norqobilov",
    regionId: "surkhandarya",
    rating: 4.7,
    reviewCount: 740,
    specialties: ["Ishonchnoma", "Vasiyatnoma"],
    nextAvailable: "Bugun, 12:30",
    avatarSeed: "sanjar12",
  },
  {
    id: "not-013",
    name: "Ulug'bek Tursunov",
    regionId: "khorezm",
    rating: 4.9,
    reviewCount: 351,
    specialties: ["Notarial tarjima", "Yer uchastkasi"],
    nextAvailable: "Ertaga, 11:30",
    avatarSeed: "ulugbek13",
  },
  {
    id: "not-014",
    name: "Dilorom Yusupova",
    regionId: "karakalpakstan",
    rating: 4.6,
    reviewCount: 179,
    specialties: ["Nikoh shartnomasi", "Meros ishlari"],
    nextAvailable: "Ertaga, 15:00",
    avatarSeed: "dilorom14",
  },
  {
    id: "not-015",
    name: "Ulug'bek Karimov",
    regionId: "surkhandarya",
    rating: 4.7,
    reviewCount: 568,
    specialties: ["Ariza-dalolatnomalar", "Biznes shartnomalari"],
    nextAvailable: "Bugun, 12:30",
    avatarSeed: "ulugbek15",
  },
  {
    id: "not-016",
    name: "Davron Yuldashov",
    regionId: "namangan",
    rating: 4.9,
    reviewCount: 345,
    specialties: ["Kredit hujjatlari", "Biznes shartnomalari"],
    nextAvailable: "Ertaga, 11:30",
    avatarSeed: "davron16",
  },
  {
    id: "not-017",
    name: "Nigora Xolmatova",
    regionId: "andijan",
    rating: 4.6,
    reviewCount: 734,
    specialties: ["Ishonchnoma", "Kredit hujjatlari"],
    nextAvailable: "Bugun, 16:45",
    avatarSeed: "nigora17",
  },
  {
    id: "not-018",
    name: "Jaloliddin Mirzayev",
    regionId: "namangan",
    rating: 4.6,
    reviewCount: 607,
    specialties: ["Vasiyatnoma", "Ko'chmas mulk"],
    nextAvailable: "Ertaga, 9:00",
    avatarSeed: "jaloliddin18",
  },
  {
    id: "not-019",
    name: "Yulduz Karimova",
    regionId: "surkhandarya",
    rating: 4.8,
    reviewCount: 817,
    specialties: ["Sud hujjatlari", "Notarial tarjima"],
    nextAvailable: "Bugun, 10:00",
    avatarSeed: "yulduz19",
  },
  {
    id: "not-020",
    name: "Alisher Ergashov",
    regionId: "samarkand",
    rating: 4.5,
    reviewCount: 128,
    specialties: ["Yer uchastkasi", "Biznes shartnomalari"],
    nextAvailable: "Bugun, 16:45",
    avatarSeed: "alisher20",
  },
  {
    id: "not-021",
    name: "Bobur Boltayov",
    regionId: "navoiy",
    rating: 4.5,
    reviewCount: 214,
    specialties: ["Ko'chmas mulk", "Ishonchnoma"],
    nextAvailable: "Ertaga, 17:30",
    avatarSeed: "bobur21",
  },
  {
    id: "not-022",
    name: "Rustam Saidov",
    regionId: "tashkent-city",
    rating: 4.8,
    reviewCount: 212,
    specialties: ["Ishonchnoma", "Ariza-dalolatnomalar"],
    nextAvailable: "Bugun, 18:15",
    avatarSeed: "rustam22",
  },
  {
    id: "not-023",
    name: "Aziza Rahimova",
    regionId: "samarkand",
    rating: 4.9,
    reviewCount: 537,
    specialties: ["Ishonchnoma", "Tashkiliy hujjatlar"],
    nextAvailable: "Ertaga, 15:00",
    avatarSeed: "aziza23",
  },
  {
    id: "not-024",
    name: "Jasur Toshov",
    regionId: "sirdaryo",
    rating: 4.7,
    reviewCount: 768,
    specialties: ["Tashkiliy hujjatlar", "Vasiyatnoma"],
    nextAvailable: "Bugun, 14:15",
    avatarSeed: "jasur24",
  },
  {
    id: "not-025",
    name: "Madina Xasanova",
    regionId: "sirdaryo",
    rating: 5.0,
    reviewCount: 836,
    specialties: ["Kredit hujjatlari", "Sud hujjatlari"],
    nextAvailable: "Ertaga, 17:30",
    avatarSeed: "madina25",
  },
  {
    id: "not-026",
    name: "Jasur Jo'rayev",
    regionId: "karakalpakstan",
    rating: 4.7,
    reviewCount: 231,
    specialties: ["Vasiyatnoma", "Sud hujjatlari"],
    nextAvailable: "Ertaga, 9:00",
    avatarSeed: "jasur26",
  },
  {
    id: "not-027",
    name: "Sabina Boltayova",
    regionId: "kashkadarya",
    rating: 4.9,
    reviewCount: 836,
    specialties: ["Ariza-dalolatnomalar", "Notarial tarjima"],
    nextAvailable: "Bugun, 16:45",
    avatarSeed: "sabina27",
  },
  {
    id: "not-028",
    name: "Nigora Toshova",
    regionId: "khorezm",
    rating: 4.8,
    reviewCount: 424,
    specialties: ["Ariza-dalolatnomalar", "Tashkiliy hujjatlar"],
    nextAvailable: "Bugun, 10:00",
    avatarSeed: "nigora28",
  },
  {
    id: "not-029",
    name: "Feruza Nuriddinova",
    regionId: "namangan",
    rating: 5.0,
    reviewCount: 517,
    specialties: ["Ariza-dalolatnomalar", "Notarial tarjima"],
    nextAvailable: "Ertaga, 9:00",
    avatarSeed: "feruza29",
  },
  {
    id: "not-030",
    name: "Dilorom Norqobilova",
    regionId: "fergana",
    rating: 4.7,
    reviewCount: 405,
    specialties: ["Ishonchnoma", "Ariza-dalolatnomalar"],
    nextAvailable: "Bugun, 16:45",
    avatarSeed: "dilorom30",
  },
  {
    id: "not-031",
    name: "Nodirbek Yusupov",
    regionId: "samarkand",
    rating: 4.9,
    reviewCount: 146,
    specialties: ["Yer uchastkasi", "Meros ishlari"],
    nextAvailable: "Bugun, 12:30",
    avatarSeed: "nodirbek31",
  },
  {
    id: "not-032",
    name: "Madina Mirzayeva",
    regionId: "jizzakh",
    rating: 4.5,
    reviewCount: 799,
    specialties: ["Yer uchastkasi", "Meros ishlari"],
    nextAvailable: "Ertaga, 11:30",
    avatarSeed: "madina32",
  },
];
